app_version: 0.4.3
behavior_configs:
- base_move_speed: 3.5
  base_wheel_speed: 2.0
  free_mode_auto_off_s: 0
  grid_action_level: subgrid
  hide_cursor_on_click: false
  hide_location: bottom_left
  initial_action_location: system_cursor
  initial_overlay_monitor: with_mouse
  move_duration_ms: 100
  move_real_cursor_with_virtual: false
  move_speed_multiplier: 5.0
  movement_easing: 0.3
  multi_action_timeout_ms: 800
  name: main_behavior
  send_escape_after_global_alt_tap__windows: true
  tap_threshold_ms: 150
  wheel_easing: 0.3
  wheel_speed_multiplier: 2.0
  wheel_step_size: 30.0
  wheel_step_size_large: 125.0
classname: AppConfig
custom_monitor_assignments:
- position_based_ztq2
debug_options: {}
display_input: none
event_tap_location: hid_head
grid_configs:
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    keys: QWERT ASDFG ZXCVB YUIOP HJKL; NM,./
    num_cells_x: 5
    num_cells_y: 6
  - border_width: 1.0
    callback: build_cell_strings
    keys: ''
    num_cells_x: 5
    num_cells_y: 6
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    keys: ''
    num_cells_x: 2
    num_cells_y: 1
  hold_subgrid_key_for_nudge: true
  name: position_based_ztq
  nudges_per_cell: 2
  strategy: subgrid
  subgrid_dims:
  - 10
  - 3
  subgrid_mouse_action_keys: 'QWERT YUIOP ASDFG HJKL; ZXCVB NM,./ '
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    keys: YUIOP HJKL; NM,./
    num_cells_x: 5
    num_cells_y: 3
  - border_width: 1.0
    callback: build_cell_strings
    keys: ''
    num_cells_x: 5
    num_cells_y: 3
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    keys: ''
    num_cells_x: 2
    num_cells_y: 1
  hold_subgrid_key_for_nudge: true
  name: position_based_ztq2
  nudges_per_cell: 3
  strategy: subgrid
  subgrid_dims:
  - 3
  - 3
  subgrid_mouse_action_keys: UPO J;L M/.
keyboard_layout:
  id: com.apple.keylayout.US
  name: U.S.
  vk_to_char:
    0:
    - a
    - A
    1:
    - s
    - S
    2:
    - d
    - D
    3:
    - f
    - F
    4:
    - h
    - H
    5:
    - g
    - G
    6:
    - z
    - Z
    7:
    - x
    - X
    8:
    - c
    - C
    9:
    - v
    - V
    10:
    - "\xA7"
    - "\xB1"
    11:
    - b
    - B
    12:
    - q
    - Q
    13:
    - w
    - W
    14:
    - e
    - E
    15:
    - r
    - R
    16:
    - y
    - Y
    17:
    - t
    - T
    18:
    - '1'
    - '!'
    19:
    - '2'
    - '@'
    20:
    - '3'
    - '#'
    21:
    - '4'
    - $
    22:
    - '6'
    - ^
    23:
    - '5'
    - '%'
    24:
    - '='
    - +
    25:
    - '9'
    - (
    26:
    - '7'
    - '&'
    27:
    - '-'
    - _
    28:
    - '8'
    - '*'
    29:
    - '0'
    - )
    30:
    - ']'
    - '}'
    31:
    - o
    - O
    32:
    - u
    - U
    33:
    - '['
    - '{'
    34:
    - i
    - I
    35:
    - p
    - P
    36: "\r"
    37:
    - l
    - L
    38:
    - j
    - J
    39:
    - ''''
    - '"'
    40:
    - k
    - K
    41:
    - ;
    - ':'
    42:
    - \
    - '|'
    43:
    - ','
    - <
    44:
    - /
    - '?'
    45:
    - n
    - N
    46:
    - m
    - M
    47:
    - .
    - '>'
    48: "\t"
    49: ' '
    50:
    - '`'
    - '~'
    51: "\b"
    52: "\x03"
    53: "\e"
    65: .
    66:
    - "\x1D"
    - '*'
    67: '*'
    69: +
    70:
    - "\x1C"
    - +
    71: "\e"
    72:
    - "\x1F"
    - '='
    75: /
    76: "\x03"
    77:
    - "\x1E"
    - /
    78: '-'
    81: '='
    82: '0'
    83: '1'
    84: '2'
    85: '3'
    86: '4'
    87: '5'
    88: '6'
    89: '7'
    91: '8'
    92: '9'
    96: "\x10"
    97: "\x10"
    98: "\x10"
    99: "\x10"
    100: "\x10"
    101: "\x10"
    102: "\x10"
    103: "\x10"
    104: "\x10"
    105: "\x10"
    106: "\x10"
    107: "\x10"
    108: "\x10"
    109: "\x10"
    110: "\x10"
    111: "\x10"
    112: "\x10"
    113: "\x10"
    114: "\x05"
    115: "\x01"
    116: "\v"
    117: "\x7F"
    118: "\x10"
    119: "\x04"
    120: "\x10"
    121: "\f"
    122: "\x10"
    123: "\x1C"
    124: "\x1D"
    125: "\x1F"
    126: "\x1E"
keymaps:
- entries:
    back click: null
    back mouse button:
    - Q
    - O
    back mouse button (w/o overlay): null
    close UI element: null
    cycle click count: '1'
    cycle font: null
    cycle font reverse: null
    cycle grid action level: null
    cycle mouse action type: null
    cycle mouse button: null
    decrease overlay opacity: null
    edit config: Tab
    enter free mode: null
    execute mouse action: Space
    execute mouse move:
    - OptionLeft tap
    - enter
    exit free mode:
    - delete
    - CommandLeft
    - cmd+shift
    - option+shift
    - ctrl+shift
    - cmd+option+ctrl
    - cmd+option+shift+ctrl+q
    - ctrl+shift
    - option+space
    forward click: null
    forward mouse button:
    - P
    - W
    forward mouse button (w/o overlay): null
    hide overlay:
    - escape
    - cmd+option+shift+ctrl+w
    - delete
    hold for back button: null
    hold for drag: CommandLeft
    hold for forward button: null
    hold for middle button: ControlLeft
    hold for move: OptionLeft
    hold for right button: OptionRight
    hold for speed decrease:
    - ShiftLeft
    - ShiftRight
    - /
    hold for speed increase:
    - ctrl
    - A
    - ;
    increase overlay opacity: null
    jump to bottom: N
    jump to left edge: null
    jump to right edge: null
    jump to top:
    - B
    - V
    left mouse button: Space
    left mouse button (w/o overlay): null
    middle click: null
    middle mouse button: ''''
    middle mouse button (w/o overlay): null
    move down:
    - K
    - D
    move left:
    - J
    - S
    move right:
    - L
    - F
    move up:
    - I
    - E
    release hold/drag: Escape
    repeat last mouse action: cmd+option+shift+ctrl+f
    right click: null
    right mouse button:
    - C
    - M
    right mouse button (w/o overlay): null
    show overlay: null
    subgrid nudge down:
    - D
    - K
    subgrid nudge left:
    - S
    - J
    subgrid nudge right:
    - F
    - L
    subgrid nudge up:
    - E
    - I
    switch monitor left: null
    switch monitor right: ShiftLeft tap
    toggle app enabled: null
    toggle continuous mode: cmd+option+shift+ctrl+d
    toggle continuous mode until closed: cmd+option+shift+ctrl+a
    toggle free mode:
    - OptionRight tap
    - cmd+option+shift+ctrl+w
    toggle overlay:
    - CommandLeft tap
    - CommandRight tap
    - cmd+option+shift+ctrl+q
    toggle overlay lock: cmd+option+shift+ctrl+s
    undo last key: Backspace
    wheel down: null
    wheel down fast: null
    wheel left: null
    wheel left fast: null
    wheel right: null
    wheel right fast: null
    wheel step down:
    - U
    - R
    wheel step down large: H
    wheel step left: null
    wheel step left large:
    - Z
    - ','
    wheel step right: null
    wheel step right large:
    - X
    - .
    wheel step up:
    - Y
    - T
    wheel step up large: G
    wheel up: null
    wheel up fast: null
  name: mac
monitor_assignment_mode: custom
name: ''
style_configs:
- always_on_subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.2
  background_rgba:
  - 0.49
  - 0.4
  - 0.0
  - 0.25
  char_spacing_cell_width_ratio: 0.2
  char_spacing_font_size_ratio: 0.5
  char_spacing_strategy: cell_width_relative
  cursor_drag_rgba:
  - 0.396078431372549
  - 0.00392156862745098
  - 1.0
  - 0.7
  cursor_move_rgba:
  - 0.00392156862745098
  - 1.0
  - 0.3215686274509804
  - 0.7
  cursor_other_rgba:
  - 1.0
  - 0.9686274509803922
  - 0.058823529411764705
  - 0.7
  cursor_rgba:
  - 0.3
  - 0.42
  - 0.58
  - 0.9
  cursor_right_button_rgba:
  - 0.8705882352941177
  - 0.058823529411764705
  - 0.058823529411764705
  - 0.7
  cursor_size: 8
  font_family: '[Apple System Font]'
  font_size_multiplier: 0.4
  font_weight: 500
  grid_line_style: lines
  grid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  highlight_animation_ms: 150
  highlight_rgba:
  - 0.21
  - 0.48
  - 0.95
  - 0.1
  name: default
  show_initial_highlight: false
  subgrid_font_size_multiplier: 0.75
  subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  subgrid_text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  text_shadow_blur_radius: 4.0
  text_shadow_offset:
  - 0.0
  - 0.0
  text_shadow_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  text_y_offset: 0.0
  window_opacity: 0.2
